### ISSUE TITLE
CItation of the package

### ISSUE THREAD

**Issue by GEJ1** [cdowd/twosamples#13]
Hello,

I'm using the package for my reasearch and I want to know how to cite it properly. 

Thank you,

best,

Gustavo.

**Comment by cdowd** [comment]
Hi Gustavo,

I appreciate it! I think it is easiest to cite the ArXiv paper. https://arxiv.org/abs/2007.01360

If you don't want purely bibtex citation details (all that ArXiv provides), google scholar has other citation styles.
https://scholar.google.com/scholar_lookup?title=A%20New%20ECDF%20Two-Sample%20Test%20Statistic&author=Connor%20Dowd&publication_date=2020/07/02&arxiv_id=2007.01360

Let me know if none of that seems to work.

Best
Connor

**Comment by GEJ1** [comment]
Thank you for your quick response. I will cite the ArXiv paper.

Best!

Gustavo.
